#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# symlink settings in
sublime_dir=~/.config/sublime-text-2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSHDOT/sublime2/User" "$sublime_dir"
